const ALERT_TYPES = {
  POT_APPROACHING_LIMIT: 'POT_APPROACHING_LIMIT',
  POT_OVER_BUDGET: 'POT_OVER_BUDGET',
  SINKING_FUND_READY: 'SINKING_FUND_READY',
  UNALLOCATED_INCOME: 'UNALLOCATED_INCOME',
  STALE_BUDGET: 'STALE_BUDGET',
  MONTH_READY_TO_LOCK: 'MONTH_READY_TO_LOCK',
  BILL_DUE: 'BILL_DUE',
  BILL_OVERDUE: 'BILL_OVERDUE',
};

module.exports = { ALERT_TYPES };
